### ISSUE TITLE
Latest MicroManager Update Breaks SPIMAcquisition

### ISSUE THREAD

**Issue by spimager** [openspim/SPIMAcquisition#29]
Hi All,

I just updated FIJI/Micromanager and now the SPIMAcquisition plugin won't open at all.

Here's the log:

2015-09-19T15:34:10.859043 tid5060 [IFO,App] Plugin command: Acquire SPIM image
2015-09-19T15:34:10.889045 tid5060 [IFO,App] Thread 16 (AWT-EventQueue-0) terminated with uncaught exception
2015-09-19T15:34:10.889045 tid5060 [IFO,App] java.lang.IllegalArgumentException: invalid range properties
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.JSlider.<init>(JSlider.java:274)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.JSlider.<init>(JSlider.java:241)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at spim.SteppedSlider.<init>(SteppedSlider.java:63)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at spim.SPIMAcquisition$20.<init>(SPIMAcquisition.java:1058)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at spim.SPIMAcquisition.makeStageSlider(SPIMAcquisition.java:1058)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at spim.SPIMAcquisition.initUI(SPIMAcquisition.java:358)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at spim.SPIMAcquisition.show(SPIMAcquisition.java:218)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager.displayPlugin(PluginManager.java:114)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager.access$100(PluginManager.java:22)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager$2.run(PluginManager.java:64)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at org.micromanager.utils.GUIUtils$3.actionPerformed(GUIUtils.java:362)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Component.processMouseEvent(Component.java:6525)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Component.processEvent(Component.java:6290)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Container.processEvent(Container.java:2234)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4881)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2292)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4703)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2278)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Window.dispatchEventImpl(Window.java:2750)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4703)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue.access$500(EventQueue.java:97)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:709)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:703)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:731)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:729)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2015-09-19T15:34:10.889045 tid5060 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dscho** [comment]
Hrm. both https://github.com/openspim/SPIMAcquisition/blob/master/src/main/java/spim/gui/component/SteppedSlider.java#L63 and https://github.com/openspim/SPIMAcquisition/blob/master/src/main/java/spim/SPIMAcquisition.java#L1058 suggest that the current source code is newer than you local plugin.

You can download the current build here: http://jenkins.imagej.net/view/OpenSPIM/job/SPIMAcquisition/

**Comment by gabrieldavisjones** [comment]
Yes, I tried loading an older version of the plugin to see if it made a difference.
I just tried the latest build then, but still receive the same error:

2015-09-19T16:58:31.085869 tid3304 [IFO,App] Plugin command: Acquire SPIM image
2015-09-19T16:58:31.116870 tid3304 [IFO,App] Thread 16 (AWT-EventQueue-0) terminated with uncaught exception
2015-09-19T16:58:31.116870 tid3304 [IFO,App] java.lang.IllegalArgumentException: invalid range properties
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.JSlider.<init>(JSlider.java:274)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.JSlider.<init>(JSlider.java:241)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at spim.gui.component.SteppedSlider.<init>(SteppedSlider.java:65)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at spim.SPIMAcquisition$20.<init>(SPIMAcquisition.java:1068)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at spim.SPIMAcquisition.makeStageSlider(SPIMAcquisition.java:1068)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at spim.SPIMAcquisition.initUI(SPIMAcquisition.java:363)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at spim.SPIMAcquisition.show(SPIMAcquisition.java:224)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager.displayPlugin(PluginManager.java:114)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager.access$100(PluginManager.java:22)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at org.micromanager.pluginmanagement.PluginManager$2.run(PluginManager.java:64)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at org.micromanager.utils.GUIUtils$3.actionPerformed(GUIUtils.java:362)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Component.processMouseEvent(Component.java:6525)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Component.processEvent(Component.java:6290)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Container.processEvent(Container.java:2234)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4881)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2292)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4703)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2278)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Window.dispatchEventImpl(Window.java:2750)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4703)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue.access$500(EventQueue.java:97)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:709)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:703)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:731)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:729)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2015-09-19T16:58:31.116870 tid3304 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dscho** [comment]
The difference is of course that the line numbers match the source code which makes it much less hard to diagnose the oroblem, don't you think?

**Comment by dscho** [comment]
The really funny part is that https://github.com/openspim/SPIMAcquisition/blob/master/src/main/java/spim/SPIMAcquisition.java#L363 looks almost identical to https://github.com/openspim/SPIMAcquisition/blob/master/src/main/java/spim/SPIMAcquisition.java#L360 so it is curious that it does not fail there already.

I would recommend to recompile with a logging statement inserted that outputs those values, or even better: debug with Eclipse as described here: http://fiji.sc/Debugging#Attaching_to_ImageJ_instances

**Comment by gabrieldavisjones** [comment]
Ok, I'll give that a try.
We're currently using the Picard high-res stage that has a step-size of .25µm and a range of 45,000.
Could that have anything to do with the range property errors?

**Comment by gabrieldavisjones** [comment]
I recompiled and discovered that the error only occurs if live view is not already open.
